# 기반 이미지를 지정합니다. 여기서는 공식 OpenJDK 이미지를 사용합니다.
FROM eclipse-temurin:17

# 작업 디렉토리를 설정합니다.
WORKDIR /app

ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

# 호스트의 JAR 파일을 컨테이너의 /app 디렉토리로 복사합니다.
COPY build/libs/gateway-service.jar app.jar

# 컨테이너가 시작될 때 실행할 명령을 지정합니다.
CMD ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-jar", "app.jar"]